version: "3"

services:
  public_web:
    image: public_web
    container_name: public_web
    build:
      context: .
      dockerfile: ./apps/public_web/Dockerfile
    ports:
      - 3001:3001
    environment:
      - NODE_ENV=production