version: "3"

services:
  # web:
  #   image: web
  #   container_name: web
  #   build:
  #     context: .
  #     dockerfile: ./apps/web/Dockerfile
  #   ports:
  #     - 3000:3000
  #   environment:
  #     - NODE_ENV=production
  public_web:
    image: public_web
    container_name: public_web
    build:
      context: .
      dockerfile: ./apps/public_web/Dockerfile
    ports:
      - 3001:3001
    environment:
      - NODE_ENV=production
