version: "3"

services:
  # docs:
  #   image: docs
  #   container_name: docs
  #   build:
  #     context: .
  #     dockerfile: ./apps/docs/Dockerfile
  #   ports:
  #     - 3002:3002
  #   environment:
  #     - NODE_ENV=production
  public_web:
    image: public_web
    container_name: public_web
    build:
      context: .
      dockerfile: ./apps/public_web/Dockerfile
    ports:
      - 3001:3001
    environment:
      - NODE_ENV=production
