version: "3"

services:
  docs:
    image: docs
    container_name: docs
    build:
      context: .
      dockerfile: ./apps/docs/Dockerfile
    ports:
      - 3001:3001
    environment:
      - NODE_ENV=production
