name: Lint
run-name: Linting the repo 🚀
on:
  pull_request_target:
    branches: [ main ]
jobs:
  lint_project:
    timeout-minutes: 60
    runs-on: self-hosted
    permissions:
      pull-requests: write
    steps:
    - run: echo "🎉 The job is linting the project"
    - uses: actions/checkout@v4
      with:
        submodules: true
        repository: ${{ github.event.pull_request_target.head.repo.full_name }}
        ref: ${{ github.event.pull_request_target.head.ref }}
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'pnpm'
    - name: Install dependencies
      run: | 
        npm install -g pnpm
        pnpm install
    - name: Lint 
      run: | 
        cd apps/web
        pnpm format
        pnpm precommit
    - name: commit
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions

            