name: Release upwithcrowd
run-name: ${{ github.actor }} is taking upwithcrowd live 🚀
on:
  push:
    branches: [ upwithcrowd ]

jobs:
  release_upwithcrowd:
    timeout-minutes: 60
    runs-on: self-hosted
    steps:
    - run: echo "🎉 Going Live!"
    - name: Release upwithcrowd
      run: ssh ubuntu "cd ~/frontend/upwithcrowd_prod && chmod 777 publish.sh && ./publish.sh 3599 upwithcrowd_prod"